server:
  jsp-servlet:
    init-parameters:
        development: true
  context-path: /EMS
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /ems1.0/
      suffix: .jsp
  profiles:
    active: test
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/mapper/*.xml
